spring:
  application:
    name: ${APP_NAME}
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA_NAME}?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${OAUTH2_CLIENT_ID_GOOGLE}
            clientSecret: ${OAUTH2_CLIENT_SECRET_GOOGLE}
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB
server:
  forward-headers-strategy: framework
poseplz:
  aws:
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ap-northeast-2
      bucket-name: ${AWS_S3_BUCKET_NAME}
  jwt:
    secret-key: ${JWT_SECRET_KEY}
  naver:
    api:
      client-id: ${NAVER_API_CLIENT_ID}
      client-secret: ${NAVER_API_CLIENT_SECRET}
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
